name: release
on:
  release:
    types: [created]
jobs:
  release:
    name: Trivy Scan Ingress
    runs-on: "ubuntu-18.04"
    env:
      IMAGE_REPO: quay.io/solo-io
      SCAN_DIR: _output/scans
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GLOO_VULN_REPORTER }}
          project_id: solo-public
          export_default_credentials: true
      - name: Build an image from Dockerfile
        id: build-docker-image
        run: |
          VERSION=$(git describe --tags | cut -c 2-)
          TAGGED_VERSION=v$(echo $VERSION) make ingress-docker
          echo "::set-output name=VERSION::$(echo $VERSION)"
      - name: Run Trivy vulnerability scanner (Ingress)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/ingress:${{ steps.build-docker-image.outputs.VERSION }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-ingress.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab (Ingress)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-ingress.sarif'
      - name: Setup Gloo Docs Output (Ingress)
        run: |
          mkdir -p ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}/
      - name: Gloo Docs (Ingress)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/ingress:${{ steps.build-docker-image.outputs.VERSION }}
          format: 'template'
          template: '@hack/utils/security_scan_report/markdown.tpl'
          output: ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}/ingress_cve_report.docgen
          severity: 'CRITICAL,HIGH'
      - name: Publish Docs (Ingress)
        run: |
          SCAN_FILE=ingress_cve_report.docgen make publish-security-scan