name: release
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  release:
    name: Release
    runs-on: "ubuntu-18.04"
    env:
      IMAGE_REPO: quay.io/solo-io
      VERSION: test
      SCAN_DIR: _output/scans/${GITHUB_REF##*/}
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build an image from Dockerfile
        run: |
          TAGGED_VERSION=v${{ env.VERSION }} make certgen-docker
      - name: Run Trivy vulnerability scanner (Certgen)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/certgen:${{ env.VERSION }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-certgen.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab (Certgen)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-certgen.sarif'
      - name: Setup Gloo Docs Output (Certgen)
        run: |
          echo ${{ env.SCAN_DIR }}
          mkdir -p ${{ env.SCAN_DIR }}
          ls ${{ env.SCAN_DIR }}
      - name: Gloo Docs (Certgen)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPO }}/certgen:${{ env.VERSION }}
          format: 'template'
          template: '@hack/utils/security_scan_report/markdown.tpl'
          output: ${{ env.SCAN_DIR }}/certgen_cve_report.docgen
          severity: 'CRITICAL,HIGH'
      - name: Publish Docs (Certgen)
        run: |
          SCAN_DIR=${{ env.SCAN_DIR }}/certgen_cve_report.docgen make publish-security-scan